/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dia.pkg2;

/**
 *
 * @author Dante
 */
public class Divisa extends javax.swing.JFrame {
    
    float CHL = (float) 0.061;
    float ARG = (float) 0.024;
    float EUR = (float) 46.8;        
    float USD = (float) 40.8;
    
    String var1;
    String var2;

    String divisa1;
    String divisa2;

    float varNum1;
    float varNum2;     

    String res;
    float conversion;
        
        

    /**
     * Creates new form Divisa
     */
    public Divisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lvlTitulo = new javax.swing.JLabel();
        TxTDivisa1 = new javax.swing.JTextField();
        TxTDivisa2 = new javax.swing.JTextField();
        cbDivisa1 = new javax.swing.JComboBox<>();
        cbDivisa2 = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lvlTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lvlTitulo.setText("Divisas");

        TxTDivisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxTDivisa1ActionPerformed(evt);
            }
        });

        TxTDivisa2.setEditable(false);

        cbDivisa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARG", "USD", "CHL", "EUR" }));
        cbDivisa1.setToolTipText("");
        cbDivisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDivisa1ActionPerformed(evt);
            }
        });

        cbDivisa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARG", "USD", "CHL", "EUR" }));

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cbDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lvlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TxTDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(TxTDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnConvertir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lvlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxTDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxTDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnConvertir)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDivisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDivisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDivisa1ActionPerformed

    private void TxTDivisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTDivisa1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TxTDivisa1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        divisa1 = (String) cbDivisa1.getSelectedItem();
        divisa2 = (String) cbDivisa2.getSelectedItem();
        
        var1 = TxTDivisa1.getText();
        var2 = TxTDivisa2.getText();
        varNum1 = Float.parseFloat(var1);
        
        //De Pesos Arg a cualquiera de las divisas
        if (divisa1 == "ARG" && divisa2 == "USD") {
            conversion = varNum1 * USD;            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "ARG" && divisa2 == "EUR") {
            conversion = varNum1 * EUR;            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "ARG" && divisa2 == "CHL") {
            conversion = varNum1 / CHL;            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "ARG" && divisa2 == "ARG") {
            conversion = varNum1;            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        //De USD a cualquiera de las divisas
        if (divisa1 == "USD" && divisa2 == "EUR") {
            conversion = (float) (varNum1 * 0.89);            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "USD" && divisa2 == "USD") {
            conversion = varNum1;            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "USD" && divisa2 == "CHL") {
            conversion = (float) (varNum1 * 687.80);            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "USD" && divisa2 == "ARG") {
            conversion = varNum1 * ARG;            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        //De EUR a cualquiera de las divisas
        
        if (divisa1 == "EUR" && divisa2 == "USD") {
            conversion = (float) (varNum1 * 1.12);            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "EUR" && divisa2 == "EUR") {
            conversion = varNum1;            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "EUR" && divisa2 == "CHL") {
            conversion = (float) (varNum1 / 771.43);            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "EUR" && divisa2 == "ARG") {
            conversion = (float) (varNum1 * 46.89);            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        //De CHL a cualquiera de las divisas
        if (divisa1 == "CHL" && divisa2 == "USD") {
            conversion = (float) (varNum1 * 0.0015);            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "CHL" && divisa2 == "EUR") {
            conversion = (float) (varNum1 * 0.0013);            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "CHL" && divisa2 == "CHL") {
            conversion = varNum1;            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
        if (divisa1 == "CHL" && divisa2 == "ARG") {
            conversion = (float) (varNum1 * 0.061);            
            res = String.valueOf(conversion);
            TxTDivisa2.setText(res);
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Divisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Divisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Divisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Divisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Divisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxTDivisa1;
    private javax.swing.JTextField TxTDivisa2;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> cbDivisa1;
    private javax.swing.JComboBox<String> cbDivisa2;
    private javax.swing.JLabel lvlTitulo;
    // End of variables declaration//GEN-END:variables
}
